Fix okhttp logger error
Exception in thread "pool-1-thread-2" java.lang.NoSuchMethodError: okhttp3.internal.platform.Platform.log(ILjava/lang/String;Ljava/lang/Throwable;)V

caused by the telegram library, see https://github.com/kotlin-telegram-bot/kotlin-telegram-bot/pull/50